version: '3'

services:
  todos_database:
    image: postgres:15.3
    container_name: tasks-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres:/var/lib/postgresql/data
